### ISSUE TITLE
Installguide

### ISSUE THREAD

**Issue by andibagandi** [ItsWasteD/Energy-Air-Bot#1]
Hi there
Thank you for your effort. How is this extension working? I installed it, visited the game.energy page and typed in the phone number in the extension. but nothing happen

**Comment by ItsWasteD** [comment]
Hello,
No problem :) Sorry you were to fast for me I wasn't able to add a README or something else until now.

But its added now hope it helps!

Btw I removed the Popup where you have to enter the number because I didn't use it.
