### ISSUE TITLE
Doesn't answer question

### ISSUE THREAD

**Issue by dexdter** [ItsWasteD/Energy-Air-Bot#5]
It doesn't answer this question: Mit welchem Holywood Star ist Mila Kunis verheiratet? Answer: Aston Kutcher.

**Comment by dexdter** [comment]
I read the code and I saw the issue: The question is there, but the answer is written false. In the code its written Ashton Kutscher, but it should be Ashton Kutcher.

**Comment by ItsWasteD** [comment]
Hello dexdter,

Yeah I know they are changing the questions and answer all the time so I have to always adapt them.

But now its fixed again :)
